In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np


import itertools
combinations = itertools.product([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], repeat=4)
interval_list = [0, 10, 20, 30, 40]

In [2]:
# Define the neural network architecture
class Classifier(nn.Module):
    
    def __init__(self, input_size, hidden_size, num_classes):
        super(Classifier, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(hidden_size, hidden_size)
        self.relu3 = nn.ReLU()
        self.fc4 = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.relu2(out)
        out = self.fc3(out)
        out = self.relu3(out)
        out = self.fc4(out)
        return out

In [3]:
# Set the hyperparameters
input_size = 4
hidden_size = 3
num_classes = 4
learning_rate = 0.01
num_epochs = 10

In [4]:
# Create an instance of the classifier
model = Classifier(input_size, hidden_size, num_classes)

In [5]:
# Set initial parameters for the linear layer
model.fc1.weight.data = torch.tensor([[ 0.0655, -0.0177, -0.1375, -0.1797],
        [ 0.2371, -0.0208,  0.0172,  0.0747],
        [ 0.1730, -0.4268,  0.1182, -0.2588]])
model.fc1.bias.data = torch.tensor([0.1859, 0.0224, 0.3914])

model.fc2.weight.data = torch.tensor([[-0.4349, -0.3517, -0.4979],
        [ 0.3674,  0.5196,  0.1202],
        [ 0.3946,  0.0655, -0.4717]])
model.fc2.bias.data = torch.tensor([-0.4927, -0.4731, -0.5731])

model.fc3.weight.data = torch.tensor([[ 0.4325, -0.3106, -0.3524],
        [ 0.0794, -0.4895,  0.4802],
        [-0.1528, -0.3796, -0.4689]])
model.fc3.bias.data = torch.tensor([0.1662, 0.4920, 0.3393])

model.fc4.weight.data = torch.tensor([[ 0.0037,  0.0709,  0.2239],
        [ 0.4758, -0.0593, -0.5652],
        [ 0.2110,  0.4942,  0.1725],
        [ 0.0611,  0.3830, -0.1682]])
model.fc4.bias.data = torch.tensor([ 0.5378, -0.1346,  0.3101, -0.3379])

In [6]:
# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

In [128]:
"""
# Define your training data and labels
train_data = torch.tensor([[4.0, 4.0, 3.0, 3.0, 3.0, 3.0, 6.0, 4.0, 1.0, 1.0, 4.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0,
                   2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 3.0, 3.0, 1.0, 2.0, 1.0, 3.0, 1.0, 1.0]])
train_labels = torch.tensor([1])
"""

'\n# Define your training data and labels\ntrain_data = torch.tensor([[4.0, 4.0, 3.0, 3.0, 3.0, 3.0, 6.0, 4.0, 1.0, 1.0, 4.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0,\n                   2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 3.0, 3.0, 1.0, 2.0, 1.0, 3.0, 1.0, 1.0]])\ntrain_labels = torch.tensor([1])\n'

In [7]:
# Print the initial model parameters
print("Initial Model Parameters:")
for name, param in model.state_dict().items():
    print(name, param)

Initial Model Parameters:
fc1.weight tensor([[ 0.0655, -0.0177, -0.1375, -0.1797],
        [ 0.2371, -0.0208,  0.0172,  0.0747],
        [ 0.1730, -0.4268,  0.1182, -0.2588]])
fc1.bias tensor([0.1859, 0.0224, 0.3914])
fc2.weight tensor([[-0.4349, -0.3517, -0.4979],
        [ 0.3674,  0.5196,  0.1202],
        [ 0.3946,  0.0655, -0.4717]])
fc2.bias tensor([-0.4927, -0.4731, -0.5731])
fc3.weight tensor([[ 0.4325, -0.3106, -0.3524],
        [ 0.0794, -0.4895,  0.4802],
        [-0.1528, -0.3796, -0.4689]])
fc3.bias tensor([0.1662, 0.4920, 0.3393])
fc4.weight tensor([[ 0.0037,  0.0709,  0.2239],
        [ 0.4758, -0.0593, -0.5652],
        [ 0.2110,  0.4942,  0.1725],
        [ 0.0611,  0.3830, -0.1682]])
fc4.bias tensor([ 0.5378, -0.1346,  0.3101, -0.3379])


In [59]:
"""
# Training loop
for epoch in range(num_epochs):
    
    # Forward pass
    outputs = model(train_data)
    loss = criterion(outputs, train_labels)
    
    # Backward and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    # Calculate training accuracy
    _, predicted_labels = torch.max(outputs, 1)
    correct_labels = (predicted_labels == train_labels).sum().item()
    accuracy = correct_labels / train_labels.size(0) * 100

    # Print the loss and accuracy every few epochs
    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}, Accuracy: {accuracy:.2f}%')
"""

"\n# Training loop\nfor epoch in range(num_epochs):\n    \n    # Forward pass\n    outputs = model(train_data)\n    loss = criterion(outputs, train_labels)\n    \n    # Backward and optimize\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()\n    \n    # Calculate training accuracy\n    _, predicted_labels = torch.max(outputs, 1)\n    correct_labels = (predicted_labels == train_labels).sum().item()\n    accuracy = correct_labels / train_labels.size(0) * 100\n\n    # Print the loss and accuracy every few epochs\n    if (epoch + 1) % 10 == 0:\n        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}, Accuracy: {accuracy:.2f}%')\n"

In [60]:
"""
# Print the updated model parameters
print("Updated Model Parameters:")
for name, param in model.state_dict().items():
    print(name, param)
"""

'\n# Print the updated model parameters\nprint("Updated Model Parameters:")\nfor name, param in model.state_dict().items():\n    print(name, param)\n'

In [8]:
def guess_the_user_value_white_box(model, w3, b3, w4, b4):
    for combination in combinations:

        X_train = []
        y_train = []

        label = len(interval_list)

        
        for number in combination:
            X_train.append(float(number))

        sum_of_combination = sum(combination)
        for i in range(len(interval_list) - 1):
            left = interval_list[i]
            right = interval_list[i + 1]
            if left <= sum_of_combination <= right:
                label = i

        # print(sum_of_combination, label)
        y_train.append(label)

        train_data = torch.tensor([X_train])
        train_labels = torch.tensor(y_train)

        print(train_data)
        print(train_labels)

               
        """
        train_data = torch.tensor([[4.0, 4.0, 3.0, 3.0, 3.0, 3.0, 6.0, 4.0, 1.0, 1.0, 4.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0,
                   2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 3.0, 3.0, 1.0, 2.0, 1.0, 3.0, 1.0, 1.0]])
        train_labels = torch.tensor([1])
        """
        
        """
        # Define your training data and labels
        train_data = torch.tensor([[4.0, 4.0, 6.0, 8.0]])
        train_labels = torch.tensor([1])
        """
        
        # Set initial parameters for the linear layer
        model.fc1.weight.data = torch.tensor([[ 0.0655, -0.0177, -0.1375, -0.1797],
        [ 0.2371, -0.0208,  0.0172,  0.0747],
        [ 0.1730, -0.4268,  0.1182, -0.2588]])
        model.fc1.bias.data = torch.tensor([0.1859, 0.0224, 0.3914])
        
        model.fc2.weight.data = torch.tensor([[-0.4349, -0.3517, -0.4979],
        [ 0.3674,  0.5196,  0.1202],
        [ 0.3946,  0.0655, -0.4717]])
        model.fc2.bias.data = torch.tensor([-0.4927, -0.4731, -0.5731])

        model.fc3.weight.data = torch.tensor([[ 0.4325, -0.3106, -0.3524],
        [ 0.0794, -0.4895,  0.4802],
        [-0.1528, -0.3796, -0.4689]])
        model.fc3.bias.data = torch.tensor([0.1662, 0.4920, 0.3393])

        model.fc4.weight.data = torch.tensor([[ 0.0037,  0.0709,  0.2239],
        [ 0.4758, -0.0593, -0.5652],
        [ 0.2110,  0.4942,  0.1725],
        [ 0.0611,  0.3830, -0.1682]])
        model.fc4.bias.data = torch.tensor([ 0.5378, -0.1346,  0.3101, -0.3379])
        
        
        """
        for name, param in model.state_dict().items():
            print(name, param)
        """
        
                
        # Training loop
        for epoch in range(num_epochs):
            
            # Forward pass
            outputs = model(train_data)
            loss = criterion(outputs, train_labels)

            # Backward and optimize
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            # Calculate training accuracy
            _, predicted_labels = torch.max(outputs, 1)
            correct_labels = (predicted_labels == train_labels).sum().item()
            accuracy = correct_labels / train_labels.size(0) * 100
           
        """
        for name, param in model.state_dict().items():
            print(name, param) 
        """
        
        
        parameter_list = list(model.state_dict().items())
        #print(parameter_list)
        
        guess_weight_f3 = parameter_list[4][1]
        guess_bias_f3 = parameter_list[5][1]
        
        guess_weight_f4 = parameter_list[6][1]
        guess_bias_f4 = parameter_list[7][1]

        b3 = np.array(b3)
        w3 = np.array(w3)
        b3 = np.round_(b3, decimals = 4)
        w3 = np.round_(w3, decimals = 4)
        
        b4 = np.array(b4)
        w4 = np.array(w4)
        b4 = np.round_(b4, decimals = 4)
        w4 = np.round_(w4, decimals = 4)
        
        guess_bias_f3 = np.array(guess_bias_f3)
        guess_weight_f3 = np.array(guess_weight_f3)
        guess_bias_f3 = np.round_(guess_bias_f3, decimals = 4)
        guess_weight_f3 = np.round_(guess_weight_f3, decimals = 4)
        
        guess_bias_f4 = np.array(guess_bias_f4)
        guess_weight_f4 = np.array(guess_weight_f4)
        guess_bias_f4 = np.round_(guess_bias_f4, decimals = 4)
        guess_weight_f4 = np.round_(guess_weight_f4, decimals = 4)
        
        #print(weight)
        #print(guess_bias)
        
        print("*"*50)
        
        #print(torch.eq(bias, guess_bias))
        #print(torch.eq(weight, guess_weight))
        
        
        if np.array_equal(b3,guess_bias_f3) and np.array_equal(w3,guess_weight_f3) and np.array_equal(b4,guess_bias_f4) and np.array_equal(w4,guess_weight_f4):
            
            return train_data
            
        

In [9]:
#parameter_list = list(model.state_dict().items())
w3 = torch.tensor([[ 0.4325, -0.3100, -0.3524],
        [ 0.0794, -0.4870,  0.4802],
        [-0.1528, -0.3781, -0.4689]])

b3 = torch.tensor([0.1722, 0.5173, 0.3538])

w4 = torch.tensor([[-0.0010,  0.0552,  0.2133],
        [ 0.4739, -0.0657, -0.5695],
        [ 0.2197,  0.5231,  0.1921],
        [ 0.0590,  0.3762, -0.1728]])

b4 = torch.tensor([ 0.5031, -0.1488,  0.3740, -0.3530])

In [10]:
guess_value = guess_the_user_value_white_box(model, w3, b3, w4, b4)
print(guess_value)

tensor([[1., 1., 1., 1.]])
tensor([0])
**************************************************
tensor([[1., 1., 1., 2.]])
tensor([0])
**************************************************
tensor([[1., 1., 1., 3.]])
tensor([0])
**************************************************
tensor([[1., 1., 1., 4.]])
tensor([0])
**************************************************
tensor([[1., 1., 1., 5.]])
tensor([0])
**************************************************
tensor([[1., 1., 1., 6.]])
tensor([0])
**************************************************
tensor([[1., 1., 1., 7.]])
tensor([1])
**************************************************
tensor([[1., 1., 1., 8.]])
tensor([1])
**************************************************
tensor([[1., 1., 1., 9.]])
tensor([1])
**************************************************
tensor([[ 1.,  1.,  1., 10.]])
tensor([1])
**************************************************
tensor([[1., 1., 2., 1.]])
tensor([0])
**************************************************
tensor

**************************************************
tensor([[ 1.,  1., 10.,  9.]])
tensor([2])
**************************************************
tensor([[ 1.,  1., 10., 10.]])
tensor([2])
**************************************************
tensor([[1., 2., 1., 1.]])
tensor([0])
**************************************************
tensor([[1., 2., 1., 2.]])
tensor([0])
**************************************************
tensor([[1., 2., 1., 3.]])
tensor([0])
**************************************************
tensor([[1., 2., 1., 4.]])
tensor([0])
**************************************************
tensor([[1., 2., 1., 5.]])
tensor([0])
**************************************************
tensor([[1., 2., 1., 6.]])
tensor([1])
**************************************************
tensor([[1., 2., 1., 7.]])
tensor([1])
**************************************************
tensor([[1., 2., 1., 8.]])
tensor([1])
**************************************************
tensor([[1., 2., 1., 9.]])
tensor([1])
**

**************************************************
tensor([[1., 3., 1., 8.]])
tensor([1])
**************************************************
tensor([[1., 3., 1., 9.]])
tensor([1])
**************************************************
tensor([[ 1.,  3.,  1., 10.]])
tensor([1])
**************************************************
tensor([[1., 3., 2., 1.]])
tensor([0])
**************************************************
tensor([[1., 3., 2., 2.]])
tensor([0])
**************************************************
tensor([[1., 3., 2., 3.]])
tensor([0])
**************************************************
tensor([[1., 3., 2., 4.]])
tensor([1])
**************************************************
tensor([[1., 3., 2., 5.]])
tensor([1])
**************************************************
tensor([[1., 3., 2., 6.]])
tensor([1])
**************************************************
tensor([[1., 3., 2., 7.]])
tensor([1])
**************************************************
tensor([[1., 3., 2., 8.]])
tensor([1])
******

**************************************************
tensor([[ 1.,  4.,  1., 10.]])
tensor([1])
**************************************************
tensor([[1., 4., 2., 1.]])
tensor([0])
**************************************************
tensor([[1., 4., 2., 2.]])
tensor([0])
**************************************************
tensor([[1., 4., 2., 3.]])
tensor([1])
**************************************************
tensor([[1., 4., 2., 4.]])
tensor([1])
**************************************************
tensor([[1., 4., 2., 5.]])
tensor([1])
**************************************************
tensor([[1., 4., 2., 6.]])
tensor([1])
**************************************************
tensor([[1., 4., 2., 7.]])
tensor([1])
**************************************************
tensor([[1., 4., 2., 8.]])
tensor([1])
**************************************************
tensor([[1., 4., 2., 9.]])
tensor([1])
**************************************************
tensor([[ 1.,  4.,  2., 10.]])
tensor([1])
**

**************************************************
tensor([[1., 5., 1., 7.]])
tensor([1])
**************************************************
tensor([[1., 5., 1., 8.]])
tensor([1])
**************************************************
tensor([[1., 5., 1., 9.]])
tensor([1])
**************************************************
tensor([[ 1.,  5.,  1., 10.]])
tensor([1])
**************************************************
tensor([[1., 5., 2., 1.]])
tensor([0])
**************************************************
tensor([[1., 5., 2., 2.]])
tensor([1])
**************************************************
tensor([[1., 5., 2., 3.]])
tensor([1])
**************************************************
tensor([[1., 5., 2., 4.]])
tensor([1])
**************************************************
tensor([[1., 5., 2., 5.]])
tensor([1])
**************************************************
tensor([[1., 5., 2., 6.]])
tensor([1])
**************************************************
tensor([[1., 5., 2., 7.]])
tensor([1])
******

**************************************************
tensor([[1., 6., 2., 3.]])
tensor([1])
**************************************************
tensor([[1., 6., 2., 4.]])
tensor([1])
**************************************************
tensor([[1., 6., 2., 5.]])
tensor([1])
**************************************************
tensor([[1., 6., 2., 6.]])
tensor([1])
**************************************************
tensor([[1., 6., 2., 7.]])
tensor([1])
**************************************************
tensor([[1., 6., 2., 8.]])
tensor([1])
**************************************************
tensor([[1., 6., 2., 9.]])
tensor([1])
**************************************************
tensor([[ 1.,  6.,  2., 10.]])
tensor([1])
**************************************************
tensor([[1., 6., 3., 1.]])
tensor([1])
**************************************************
tensor([[1., 6., 3., 2.]])
tensor([1])
**************************************************
tensor([[1., 6., 3., 3.]])
tensor([1])
******

tensor([[1., 7., 2., 6.]])
tensor([1])
**************************************************
tensor([[1., 7., 2., 7.]])
tensor([1])
**************************************************
tensor([[1., 7., 2., 8.]])
tensor([1])
**************************************************
tensor([[1., 7., 2., 9.]])
tensor([1])
**************************************************
tensor([[ 1.,  7.,  2., 10.]])
tensor([2])
**************************************************
tensor([[1., 7., 3., 1.]])
tensor([1])
**************************************************
tensor([[1., 7., 3., 2.]])
tensor([1])
**************************************************
tensor([[1., 7., 3., 3.]])
tensor([1])
**************************************************
tensor([[1., 7., 3., 4.]])
tensor([1])
**************************************************
tensor([[1., 7., 3., 5.]])
tensor([1])
**************************************************
tensor([[1., 7., 3., 6.]])
tensor([1])
**************************************************
tensor

**************************************************
tensor([[1., 8., 2., 3.]])
tensor([1])
**************************************************
tensor([[1., 8., 2., 4.]])
tensor([1])
**************************************************
tensor([[1., 8., 2., 5.]])
tensor([1])
**************************************************
tensor([[1., 8., 2., 6.]])
tensor([1])
**************************************************
tensor([[1., 8., 2., 7.]])
tensor([1])
**************************************************
tensor([[1., 8., 2., 8.]])
tensor([1])
**************************************************
tensor([[1., 8., 2., 9.]])
tensor([2])
**************************************************
tensor([[ 1.,  8.,  2., 10.]])
tensor([2])
**************************************************
tensor([[1., 8., 3., 1.]])
tensor([1])
**************************************************
tensor([[1., 8., 3., 2.]])
tensor([1])
**************************************************
tensor([[1., 8., 3., 3.]])
tensor([1])
******

**************************************************
tensor([[1., 9., 2., 8.]])
tensor([2])
**************************************************
tensor([[1., 9., 2., 9.]])
tensor([2])
**************************************************
tensor([[ 1.,  9.,  2., 10.]])
tensor([2])
**************************************************
tensor([[1., 9., 3., 1.]])
tensor([1])
**************************************************
tensor([[1., 9., 3., 2.]])
tensor([1])
**************************************************
tensor([[1., 9., 3., 3.]])
tensor([1])
**************************************************
tensor([[1., 9., 3., 4.]])
tensor([1])
**************************************************
tensor([[1., 9., 3., 5.]])
tensor([1])
**************************************************
tensor([[1., 9., 3., 6.]])
tensor([1])
**************************************************
tensor([[1., 9., 3., 7.]])
tensor([2])
**************************************************
tensor([[1., 9., 3., 8.]])
tensor([2])
******

**************************************************
tensor([[ 1., 10.,  2.,  4.]])
tensor([1])
**************************************************
tensor([[ 1., 10.,  2.,  5.]])
tensor([1])
**************************************************
tensor([[ 1., 10.,  2.,  6.]])
tensor([1])
**************************************************
tensor([[ 1., 10.,  2.,  7.]])
tensor([2])
**************************************************
tensor([[ 1., 10.,  2.,  8.]])
tensor([2])
**************************************************
tensor([[ 1., 10.,  2.,  9.]])
tensor([2])
**************************************************
tensor([[ 1., 10.,  2., 10.]])
tensor([2])
**************************************************
tensor([[ 1., 10.,  3.,  1.]])
tensor([1])
**************************************************
tensor([[ 1., 10.,  3.,  2.]])
tensor([1])
**************************************************
tensor([[ 1., 10.,  3.,  3.]])
tensor([1])
**************************************************
tensor([[

**************************************************
tensor([[ 2.,  1.,  1., 10.]])
tensor([1])
**************************************************
tensor([[2., 1., 2., 1.]])
tensor([0])
**************************************************
tensor([[2., 1., 2., 2.]])
tensor([0])
**************************************************
tensor([[2., 1., 2., 3.]])
tensor([0])
**************************************************
tensor([[2., 1., 2., 4.]])
tensor([0])
**************************************************
tensor([[2., 1., 2., 5.]])
tensor([1])
**************************************************
tensor([[2., 1., 2., 6.]])
tensor([1])
**************************************************
tensor([[2., 1., 2., 7.]])
tensor([1])
**************************************************
tensor([[2., 1., 2., 8.]])
tensor([1])
**************************************************
tensor([[2., 1., 2., 9.]])
tensor([1])
**************************************************
tensor([[ 2.,  1.,  2., 10.]])
tensor([1])
**

**************************************************
tensor([[2., 2., 1., 5.]])
tensor([1])
**************************************************
tensor([[2., 2., 1., 6.]])
tensor([1])
**************************************************
tensor([[2., 2., 1., 7.]])
tensor([1])
**************************************************
tensor([[2., 2., 1., 8.]])
tensor([1])
**************************************************
tensor([[2., 2., 1., 9.]])
tensor([1])
**************************************************
tensor([[ 2.,  2.,  1., 10.]])
tensor([1])
**************************************************
tensor([[2., 2., 2., 1.]])
tensor([0])
**************************************************
tensor([[2., 2., 2., 2.]])
tensor([0])
**************************************************
tensor([[2., 2., 2., 3.]])
tensor([0])
**************************************************
tensor([[2., 2., 2., 4.]])
tensor([1])
**************************************************
tensor([[2., 2., 2., 5.]])
tensor([1])
******

**************************************************
tensor([[2., 3., 2., 3.]])
tensor([1])
**************************************************
tensor([[2., 3., 2., 4.]])
tensor([1])
**************************************************
tensor([[2., 3., 2., 5.]])
tensor([1])
**************************************************
tensor([[2., 3., 2., 6.]])
tensor([1])
**************************************************
tensor([[2., 3., 2., 7.]])
tensor([1])
**************************************************
tensor([[2., 3., 2., 8.]])
tensor([1])
**************************************************
tensor([[2., 3., 2., 9.]])
tensor([1])
**************************************************
tensor([[ 2.,  3.,  2., 10.]])
tensor([1])
**************************************************
tensor([[2., 3., 3., 1.]])
tensor([0])
**************************************************
tensor([[2., 3., 3., 2.]])
tensor([1])
**************************************************
tensor([[2., 3., 3., 3.]])
tensor([1])
******

**************************************************
tensor([[2., 4., 1., 9.]])
tensor([1])
**************************************************
tensor([[ 2.,  4.,  1., 10.]])
tensor([1])
**************************************************
tensor([[2., 4., 2., 1.]])
tensor([0])
**************************************************
tensor([[2., 4., 2., 2.]])
tensor([1])
**************************************************
tensor([[2., 4., 2., 3.]])
tensor([1])
**************************************************
tensor([[2., 4., 2., 4.]])
tensor([1])
**************************************************
tensor([[2., 4., 2., 5.]])
tensor([1])
**************************************************
tensor([[2., 4., 2., 6.]])
tensor([1])
**************************************************
tensor([[2., 4., 2., 7.]])
tensor([1])
**************************************************
tensor([[2., 4., 2., 8.]])
tensor([1])
**************************************************
tensor([[2., 4., 2., 9.]])
tensor([1])
******

**************************************************
tensor([[2., 5., 1., 7.]])
tensor([1])
**************************************************
tensor([[2., 5., 1., 8.]])
tensor([1])
**************************************************
tensor([[2., 5., 1., 9.]])
tensor([1])
**************************************************
tensor([[ 2.,  5.,  1., 10.]])
tensor([1])
**************************************************
tensor([[2., 5., 2., 1.]])
tensor([1])
**************************************************
tensor([[2., 5., 2., 2.]])
tensor([1])
**************************************************
tensor([[2., 5., 2., 3.]])
tensor([1])
**************************************************
tensor([[2., 5., 2., 4.]])
tensor([1])
**************************************************
tensor([[2., 5., 2., 5.]])
tensor([1])
**************************************************
tensor([[2., 5., 2., 6.]])
tensor([1])
**************************************************
tensor([[2., 5., 2., 7.]])
tensor([1])
******

**************************************************
tensor([[ 2.,  6.,  1., 10.]])
tensor([1])
**************************************************
tensor([[2., 6., 2., 1.]])
tensor([1])
**************************************************
tensor([[2., 6., 2., 2.]])
tensor([1])
**************************************************
tensor([[2., 6., 2., 3.]])
tensor([1])
**************************************************
tensor([[2., 6., 2., 4.]])
tensor([1])
**************************************************
tensor([[2., 6., 2., 5.]])
tensor([1])
**************************************************
tensor([[2., 6., 2., 6.]])
tensor([1])
**************************************************
tensor([[2., 6., 2., 7.]])
tensor([1])
**************************************************
tensor([[2., 6., 2., 8.]])
tensor([1])
**************************************************
tensor([[2., 6., 2., 9.]])
tensor([1])
**************************************************
tensor([[ 2.,  6.,  2., 10.]])
tensor([2])
**

**************************************************
tensor([[2., 7., 2., 1.]])
tensor([1])
**************************************************
tensor([[2., 7., 2., 2.]])
tensor([1])
**************************************************
tensor([[2., 7., 2., 3.]])
tensor([1])
**************************************************
tensor([[2., 7., 2., 4.]])
tensor([1])
**************************************************
tensor([[2., 7., 2., 5.]])
tensor([1])
**************************************************
tensor([[2., 7., 2., 6.]])
tensor([1])
**************************************************
tensor([[2., 7., 2., 7.]])
tensor([1])
**************************************************
tensor([[2., 7., 2., 8.]])
tensor([1])
**************************************************
tensor([[2., 7., 2., 9.]])
tensor([2])
**************************************************
tensor([[ 2.,  7.,  2., 10.]])
tensor([2])
**************************************************
tensor([[2., 7., 3., 1.]])
tensor([1])
******

**************************************************
tensor([[2., 8., 1., 9.]])
tensor([2])
**************************************************
tensor([[ 2.,  8.,  1., 10.]])
tensor([2])
**************************************************
tensor([[2., 8., 2., 1.]])
tensor([1])
**************************************************
tensor([[2., 8., 2., 2.]])
tensor([1])
**************************************************
tensor([[2., 8., 2., 3.]])
tensor([1])
**************************************************
tensor([[2., 8., 2., 4.]])
tensor([1])
**************************************************
tensor([[2., 8., 2., 5.]])
tensor([1])
**************************************************
tensor([[2., 8., 2., 6.]])
tensor([1])
**************************************************
tensor([[2., 8., 2., 7.]])
tensor([1])
**************************************************
tensor([[2., 8., 2., 8.]])
tensor([2])
**************************************************
tensor([[2., 8., 2., 9.]])
tensor([2])
******

**************************************************
tensor([[2., 9., 1., 5.]])
tensor([1])
**************************************************
tensor([[2., 9., 1., 6.]])
tensor([1])
**************************************************
tensor([[2., 9., 1., 7.]])
tensor([1])
**************************************************
tensor([[2., 9., 1., 8.]])
tensor([2])
**************************************************
tensor([[2., 9., 1., 9.]])
tensor([2])
**************************************************
tensor([[ 2.,  9.,  1., 10.]])
tensor([2])
**************************************************
tensor([[2., 9., 2., 1.]])
tensor([1])
**************************************************
tensor([[2., 9., 2., 2.]])
tensor([1])
**************************************************
tensor([[2., 9., 2., 3.]])
tensor([1])
**************************************************
tensor([[2., 9., 2., 4.]])
tensor([1])
**************************************************
tensor([[2., 9., 2., 5.]])
tensor([1])
******

**************************************************
tensor([[ 2., 10.,  1.,  6.]])
tensor([1])
**************************************************
tensor([[ 2., 10.,  1.,  7.]])
tensor([2])
**************************************************
tensor([[ 2., 10.,  1.,  8.]])
tensor([2])
**************************************************
tensor([[ 2., 10.,  1.,  9.]])
tensor([2])
**************************************************
tensor([[ 2., 10.,  1., 10.]])
tensor([2])
**************************************************
tensor([[ 2., 10.,  2.,  1.]])
tensor([1])
**************************************************
tensor([[ 2., 10.,  2.,  2.]])
tensor([1])
**************************************************
tensor([[ 2., 10.,  2.,  3.]])
tensor([1])
**************************************************
tensor([[ 2., 10.,  2.,  4.]])
tensor([1])
**************************************************
tensor([[ 2., 10.,  2.,  5.]])
tensor([1])
**************************************************
tensor([[

**************************************************
tensor([[3., 1., 1., 1.]])
tensor([0])
**************************************************
tensor([[3., 1., 1., 2.]])
tensor([0])
**************************************************
tensor([[3., 1., 1., 3.]])
tensor([0])
**************************************************
tensor([[3., 1., 1., 4.]])
tensor([0])
**************************************************
tensor([[3., 1., 1., 5.]])
tensor([1])
**************************************************
tensor([[3., 1., 1., 6.]])
tensor([1])
**************************************************
tensor([[3., 1., 1., 7.]])
tensor([1])
**************************************************
tensor([[3., 1., 1., 8.]])
tensor([1])
**************************************************
tensor([[3., 1., 1., 9.]])
tensor([1])
**************************************************
tensor([[ 3.,  1.,  1., 10.]])
tensor([1])
**************************************************
tensor([[3., 1., 2., 1.]])
tensor([0])
******

**************************************************
tensor([[3., 2., 1., 1.]])
tensor([0])
**************************************************
tensor([[3., 2., 1., 2.]])
tensor([0])
**************************************************
tensor([[3., 2., 1., 3.]])
tensor([0])
**************************************************
tensor([[3., 2., 1., 4.]])
tensor([1])
**************************************************
tensor([[3., 2., 1., 5.]])
tensor([1])
**************************************************
tensor([[3., 2., 1., 6.]])
tensor([1])
**************************************************
tensor([[3., 2., 1., 7.]])
tensor([1])
**************************************************
tensor([[3., 2., 1., 8.]])
tensor([1])
**************************************************
tensor([[3., 2., 1., 9.]])
tensor([1])
**************************************************
tensor([[ 3.,  2.,  1., 10.]])
tensor([1])
**************************************************
tensor([[3., 2., 2., 1.]])
tensor([0])
******

**************************************************
tensor([[ 3.,  2., 10., 10.]])
tensor([2])
**************************************************
tensor([[3., 3., 1., 1.]])
tensor([0])
**************************************************
tensor([[3., 3., 1., 2.]])
tensor([0])
**************************************************
tensor([[3., 3., 1., 3.]])
tensor([1])
**************************************************
tensor([[3., 3., 1., 4.]])
tensor([1])
**************************************************
tensor([[3., 3., 1., 5.]])
tensor([1])
**************************************************
tensor([[3., 3., 1., 6.]])
tensor([1])
**************************************************
tensor([[3., 3., 1., 7.]])
tensor([1])
**************************************************
tensor([[3., 3., 1., 8.]])
tensor([1])
**************************************************
tensor([[3., 3., 1., 9.]])
tensor([1])
**************************************************
tensor([[ 3.,  3.,  1., 10.]])
tensor([1])
**

tensor([[ 3.,  3., 10.,  7.]])
tensor([2])
**************************************************
tensor([[ 3.,  3., 10.,  8.]])
tensor([2])
**************************************************
tensor([[ 3.,  3., 10.,  9.]])
tensor([2])
**************************************************
tensor([[ 3.,  3., 10., 10.]])
tensor([2])
**************************************************
tensor([[3., 4., 1., 1.]])
tensor([0])
**************************************************
tensor([[3., 4., 1., 2.]])
tensor([1])
**************************************************
tensor([[3., 4., 1., 3.]])
tensor([1])
**************************************************
tensor([[3., 4., 1., 4.]])
tensor([1])
**************************************************
tensor([[3., 4., 1., 5.]])
tensor([1])
**************************************************
tensor([[3., 4., 1., 6.]])
tensor([1])
**************************************************
tensor([[3., 4., 1., 7.]])
tensor([1])
*********************************************

**************************************************
tensor([[ 3.,  4., 10.,  5.]])
tensor([2])
**************************************************
tensor([[ 3.,  4., 10.,  6.]])
tensor([2])
**************************************************
tensor([[ 3.,  4., 10.,  7.]])
tensor([2])
**************************************************
tensor([[ 3.,  4., 10.,  8.]])
tensor([2])
**************************************************
tensor([[ 3.,  4., 10.,  9.]])
tensor([2])
**************************************************
tensor([[ 3.,  4., 10., 10.]])
tensor([2])
**************************************************
tensor([[3., 5., 1., 1.]])
tensor([1])
**************************************************
tensor([[3., 5., 1., 2.]])
tensor([1])
**************************************************
tensor([[3., 5., 1., 3.]])
tensor([1])
**************************************************
tensor([[3., 5., 1., 4.]])
tensor([1])
**************************************************
tensor([[3., 5., 1., 5.]]

**************************************************
tensor([[ 3.,  5., 10.,  2.]])
tensor([2])
**************************************************
tensor([[ 3.,  5., 10.,  3.]])
tensor([2])
**************************************************
tensor([[ 3.,  5., 10.,  4.]])
tensor([2])
**************************************************
tensor([[ 3.,  5., 10.,  5.]])
tensor([2])
**************************************************
tensor([[ 3.,  5., 10.,  6.]])
tensor([2])
**************************************************
tensor([[ 3.,  5., 10.,  7.]])
tensor([2])
**************************************************
tensor([[ 3.,  5., 10.,  8.]])
tensor([2])
**************************************************
tensor([[ 3.,  5., 10.,  9.]])
tensor([2])
**************************************************
tensor([[ 3.,  5., 10., 10.]])
tensor([2])
**************************************************
tensor([[3., 6., 1., 1.]])
tensor([1])
**************************************************
tensor([[3., 

**************************************************
tensor([[ 3.,  6., 10.,  5.]])
tensor([2])
**************************************************
tensor([[ 3.,  6., 10.,  6.]])
tensor([2])
**************************************************
tensor([[ 3.,  6., 10.,  7.]])
tensor([2])
**************************************************
tensor([[ 3.,  6., 10.,  8.]])
tensor([2])
**************************************************
tensor([[ 3.,  6., 10.,  9.]])
tensor([2])
**************************************************
tensor([[ 3.,  6., 10., 10.]])
tensor([2])
**************************************************
tensor([[3., 7., 1., 1.]])
tensor([1])
**************************************************
tensor([[3., 7., 1., 2.]])
tensor([1])
**************************************************
tensor([[3., 7., 1., 3.]])
tensor([1])
**************************************************
tensor([[3., 7., 1., 4.]])
tensor([1])
**************************************************
tensor([[3., 7., 1., 5.]]

**************************************************
tensor([[ 3.,  7., 10.,  6.]])
tensor([2])
**************************************************
tensor([[ 3.,  7., 10.,  7.]])
tensor([2])
**************************************************
tensor([[ 3.,  7., 10.,  8.]])
tensor([2])
**************************************************
tensor([[ 3.,  7., 10.,  9.]])
tensor([2])
**************************************************
tensor([[ 3.,  7., 10., 10.]])
tensor([3])
**************************************************
tensor([[3., 8., 1., 1.]])
tensor([1])
**************************************************
tensor([[3., 8., 1., 2.]])
tensor([1])
**************************************************
tensor([[3., 8., 1., 3.]])
tensor([1])
**************************************************
tensor([[3., 8., 1., 4.]])
tensor([1])
**************************************************
tensor([[3., 8., 1., 5.]])
tensor([1])
**************************************************
tensor([[3., 8., 1., 6.]])
te

**************************************************
tensor([[3., 9., 2., 1.]])
tensor([1])
**************************************************
tensor([[3., 9., 2., 2.]])
tensor([1])
**************************************************
tensor([[3., 9., 2., 3.]])
tensor([1])
**************************************************
tensor([[3., 9., 2., 4.]])
tensor([1])
**************************************************
tensor([[3., 9., 2., 5.]])
tensor([1])
**************************************************
tensor([[3., 9., 2., 6.]])
tensor([2])
**************************************************
tensor([[3., 9., 2., 7.]])
tensor([2])
**************************************************
tensor([[3., 9., 2., 8.]])
tensor([2])
**************************************************
tensor([[3., 9., 2., 9.]])
tensor([2])
**************************************************
tensor([[ 3.,  9.,  2., 10.]])
tensor([2])
**************************************************
tensor([[3., 9., 3., 1.]])
tensor([1])
******

**************************************************
tensor([[ 3., 10.,  4.,  4.]])
tensor([2])
**************************************************
tensor([[ 3., 10.,  4.,  5.]])
tensor([2])
**************************************************
tensor([[ 3., 10.,  4.,  6.]])
tensor([2])
**************************************************
tensor([[ 3., 10.,  4.,  7.]])
tensor([2])
**************************************************
tensor([[ 3., 10.,  4.,  8.]])
tensor([2])
**************************************************
tensor([[ 3., 10.,  4.,  9.]])
tensor([2])
**************************************************
tensor([[ 3., 10.,  4., 10.]])
tensor([2])
**************************************************
tensor([[ 3., 10.,  5.,  1.]])
tensor([1])
**************************************************
tensor([[ 3., 10.,  5.,  2.]])
tensor([2])
**************************************************
tensor([[ 3., 10.,  5.,  3.]])
tensor([2])
**************************************************
tensor([[

**************************************************
tensor([[4., 1., 6., 1.]])
tensor([1])
**************************************************
tensor([[4., 1., 6., 2.]])
tensor([1])
**************************************************
tensor([[4., 1., 6., 3.]])
tensor([1])
**************************************************
tensor([[4., 1., 6., 4.]])
tensor([1])
**************************************************
tensor([[4., 1., 6., 5.]])
tensor([1])
**************************************************
tensor([[4., 1., 6., 6.]])
tensor([1])
**************************************************
tensor([[4., 1., 6., 7.]])
tensor([1])
**************************************************
tensor([[4., 1., 6., 8.]])
tensor([1])
**************************************************
tensor([[4., 1., 6., 9.]])
tensor([2])
**************************************************
tensor([[ 4.,  1.,  6., 10.]])
tensor([2])
**************************************************
tensor([[4., 1., 7., 1.]])
tensor([1])
******

**************************************************
tensor([[4., 2., 8., 7.]])
tensor([2])
**************************************************
tensor([[4., 2., 8., 8.]])
tensor([2])
**************************************************
tensor([[4., 2., 8., 9.]])
tensor([2])
**************************************************
tensor([[ 4.,  2.,  8., 10.]])
tensor([2])
**************************************************
tensor([[4., 2., 9., 1.]])
tensor([1])
**************************************************
tensor([[4., 2., 9., 2.]])
tensor([1])
**************************************************
tensor([[4., 2., 9., 3.]])
tensor([1])
**************************************************
tensor([[4., 2., 9., 4.]])
tensor([1])
**************************************************
tensor([[4., 2., 9., 5.]])
tensor([2])
**************************************************
tensor([[4., 2., 9., 6.]])
tensor([2])
**************************************************
tensor([[4., 2., 9., 7.]])
tensor([2])
******

**************************************************
tensor([[4., 4., 1., 2.]])
tensor([1])
**************************************************
tensor([[4., 4., 1., 3.]])
tensor([1])
**************************************************
tensor([[4., 4., 1., 4.]])
tensor([1])
**************************************************
tensor([[4., 4., 1., 5.]])
tensor([1])
**************************************************
tensor([[4., 4., 1., 6.]])
tensor([1])
**************************************************
tensor([[4., 4., 1., 7.]])
tensor([1])
**************************************************
tensor([[4., 4., 1., 8.]])
tensor([1])
**************************************************
tensor([[4., 4., 1., 9.]])
tensor([1])
**************************************************
tensor([[ 4.,  4.,  1., 10.]])
tensor([1])
**************************************************
tensor([[4., 4., 2., 1.]])
tensor([1])
**************************************************
tensor([[4., 4., 2., 2.]])
tensor([1])
******